version: "3.7"

services:
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  alica-messages-tp:
    image: sst/sawtooth-alica-messages-tp:latest
    container_name: sawtooth-alica-messages-tp
    depends_on:
      - validator
    entrypoint: alica-messages-tp -C tcp://validator:4004

  alica-messages-client:
    image: sst/sawtooth-alica-messages-client:latest
    container_name: sawtooth-alica-messages-client
    depends_on:
      - alica-messages-tp
    entrypoint: bash -c "tail -f /dev/null"

  validator:
    image: hyperledger/sawtooth-validator:latest
    container_name: sawtooth-validator
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:latest
    container_name: sawtooth-devmode-engine
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050

  rest-api:
    image: hyperledger/sawtooth-rest-api:latest
    container_name: sawtooth-rest-api
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008

  shell:
    image: hyperledger/sawtooth-all:latest
    container_name: sawtooth-shell
    depends_on:
      - rest-api
    entrypoint: "bash -c \"\
      sawtooth keygen && \
      tail -f /dev/null \
      \""
